apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openclaw.yaml
configMapGenerator:
  - name: openclaw-values
    namespace: flux-system
    files:
      - values.yaml=openclaw-values.yaml
# Copy kustomizeconfig if specific transformations were needed for Harbor
# configurations:
#   - kustomizeconfig.yaml
