apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentsonly
resources:
  - agentsonly.yaml
  - proxmox-secret.yaml
configMapGenerator:
  - name: agentsonly-values
    files:
      - values.yaml=agentsonly-values.yaml
configurations:
  - kustomizeconfig.yaml
