apiVersion: ENC[AES256_GCM,data:vqU=,iv:uVMNUz9ss4N63vE0O+yQ4KPCo2CSdchWYmrAJZ/Q+bs=,tag:a6h86LWwUP4d6I3t4919CQ==,type:str]
kind: ENC[AES256_GCM,data:mI6IgO++,iv:JNCt6K0sZf+sKC0EhSIEc7e/mu2e5zi1Ux4J5eMG6Mc=,tag:hdZcHCjZ5yx5T2WCBvDdyA==,type:str]
metadata:
    labels:
        cluster.x-k8s.io/provider: ENC[AES256_GCM,data:dGLg1aJYEuFsPByEeF6YPFar6eTxbw==,iv:w8LGIfbviI+WhE+XonS1NzCGWkw/gUgZkm58bL1y1yc=,tag:uTGsJrVUcUqiwXb5MQExhw==,type:str]
        clusterctl.cluster.x-k8s.io: ""
        platform.ionos.com/secret-type: ENC[AES256_GCM,data:bASU6mqUtfPwVF5bqnobyFnBYg==,iv:zaHj2nGE5D+gf/xuP+4BvI3X6QIL+eShTzNqjiTDHTE=,tag:Ouj3ZITDUCKe8Ilh//jr1g==,type:str]
    name: ENC[AES256_GCM,data:Ovb6ncG/t4XbxwdoJnzogT0Yripb4Fw3xYs=,iv:gJTv9POZuTojY/HROmhLemX4K+P7jjUHMPNN9pLsuSs=,tag:iblg8A1uwKcN4xbUG/IB2A==,type:str]
    namespace: ENC[AES256_GCM,data:g7M2YZt0/G3ylg==,iv:1mMZNIDaaO6leHTLTqARH67mZsxIJK7etTDdxN9qgeU=,tag:f14wNcfgd3Vnrt37lb26WQ==,type:str]
stringData:
    secret: ENC[AES256_GCM,data:e8J8PtealH/NR1usgvjD/88aIuiRarwsRHNO0chZ31UnIqCA,iv:Dp5SPv0+bFG6BVcLWI7Kg0rHAD3nQvl+FCIDpWFDr/w=,tag:pe5c/dTookSrCRXO5xoqew==,type:str]
    token: ENC[AES256_GCM,data:VGAIJMVT2RhZhtNQMg==,iv:rlAHTLR0mWGGrU0qHVqI7649lN15W4LeEijQgVxyMJY=,tag:nnGNq4iuDCpv65cnQmT/qw==,type:str]
    url: ENC[AES256_GCM,data:b5+gZeYyZPBdZT7Ik8P2ms4CuVVFg/JQnA==,iv:FO8RVS9LKmQgwZNJWH8WblrfJjQMbD10kaFDEVJH0PU=,tag:DoRrGZTVyEsWLSiHF/KpSg==,type:str]
sops:
    age:
        - recipient: age132zrzn35y4scdlcr0uale2p2x8ntta9zv40xfvyzrl4ra4j6df3scyf2dd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcE92bXpZRlM0ZTFpWFU0
            SXpkOGsyWTVGVWRWdFJjLzlOTGFPT3RkeVFJCkJjNXIyVWtwejU0L3kvMUo0S0FJ
            ZkxHQ0xwSnJjbUlDZEEvdytqcHdQQTAKLS0tIDA2UjdaVWVnTjNweFdBY3FtM0lP
            ZHlKbFRlNnB5SmZ0R3pZUGJRb3RsQ28K4/fOmw+eEj/pkc341KLMmfJXyZx4iO0W
            0N2T5jZsQz20rzOGU201P2ARUpMFWSSnP9VEjYXKRnM7mQ8Q+RWnag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:30:40Z"
    mac: ENC[AES256_GCM,data:iapDC2bwyPR5mRs1r0HRUNe/LEtwvlssq8XbXUcE6B34ldhBRDCWF1B5m3/a2Xxx7gUMmgum81zI6EQpovtm2ETUFP2J8rum0Lb4A4EWNN0r4xiShCZO0jplYL6T2dFSkgpdXYDROzlBH2oQ01UrIO4Xbx0l9COJgo1lq8ZbGfQ=,iv:HiY0sV7iwSkwdA7TTRKa6vx/tTVdLSu6F5msv0VS+lE=,tag:9vxuXNMKFrAmpW4NqgBJZw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
