apiVersion: v1
kind: Secret
metadata:
    labels:
        cluster.x-k8s.io/provider: infrastructure-proxmox
        clusterctl.cluster.x-k8s.io: ""
        platform.ionos.com/secret-type: proxmox-credentials
    name: capmox-manager-credentials
    namespace: agentsonly
stringData:
    secret: ENC[AES256_GCM,data:SX3/E0xig+m72CJXdI98jY4C2uxUq2mTCm0Rqwmk38//gPHi,iv:Ox+t+d8D+CK9KAt7bq0sdd7SdKZZidEbIfJ8I0DJNiw=,tag:Kstx8kXed4jUc3c8VAHUdg==,type:str]
    token: ENC[AES256_GCM,data:bNd0+tug2UWiJSZFZQ==,iv:TRYSOCrNjzjDVxoJEpBT4/85wbd08cLkhB3JU8lmmdo=,tag:obf57nYlOLcks4xi31WYzA==,type:str]
    url: ENC[AES256_GCM,data:E99loGCa2CFfd0P40zKNxMA6A0MVRKyLhw==,iv:Vq9YqzVkzZnRscOGFgWboGDVRk+0UdLr03JWt7Dn1Hg=,tag:BDLXdXuHYl58/i+7dFg1VA==,type:str]
sops:
    age:
        - recipient: age132zrzn35y4scdlcr0uale2p2x8ntta9zv40xfvyzrl4ra4j6df3scyf2dd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSmVhQzNuczMxT29rbmVo
            T1A1L3dSRldCSEtJcjcvUHlRWUszVFNjMERRClAvdVc3aUxoN09lRVlFbkpjZW1p
            aElCa1pRd3RmSENyV1JwTzFsTE9yVGcKLS0tIEJaTCtvNXF6dFh0RVVXOUFFNWYw
            aVNxdHlNYWswd1ljdWZSWVhEQUg4UjgKBfBUZw0qcCi69KXUZyd3O5MDq7bp6/ir
            eXJcBqNO2iqQ0AM+ZHlPsAssOhfNx4YrAIZJ1OXgugsokXV/jfnGaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T22:23:10Z"
    mac: ENC[AES256_GCM,data:R/Ab3yPh4wFuwJ4YQfsBOuymjK0EyNGkJdZ76dtaBHn2xulnAjLBU2WlW7YV5AF059PTHNqh2kDsCfy1jB1A5TxNI56IXjb40ooMZcCy/y3D/ztHIz3LGcJ5UkdejinQ/pxcbZbdsFc3Wg77drzn9f6uAgOO3lbq0f+X/pXSy+M=,iv:rvSXbE3KHq8K1JHQiWwN24lGxyxhxfCrGK8AlaSGFPk=,tag:awHl0Cy82Vs/NLBW4jrjgg==,type:str]
    encrypted_regex: ^(secret|token|url)$
    version: 3.11.0
