---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  gatewayClassName: cilium
  listeners:
  - hostname: harbor.podzone.cloud
    name: harbor-podzone-cloud-http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - hostname: harbor.podzone.cloud
    name: harbor-podzone-cloud
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: harbor-secret
    allowedRoutes:
      namespaces:
        from: All

  - hostname: management-hubble.podzone.cloud
    name: management-hubble-podzone-cloud-http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - hostname: management-hubble.podzone.cloud
    name: management-hubble-podzone-cloud
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: management-hubble-secret
    allowedRoutes:
      namespaces:
        from: All

  - hostname: linstor.podzone.cloud
    name: management-linstor-podzone-cloud-http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - hostname: management-linstor.podzone.cloud
    name: management-linstor-podzone-cloud
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: management-linstor-secret
    allowedRoutes:
      namespaces:
        from: All

---
apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: martinjcolley@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: gateway
                namespace: kube-system
                kind: Gateway
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble
  namespace: kube-system
spec:
  hostnames:
  - management-hubble.podzone.cloud
  parentRefs:
  - name: gateway
  rules:
  - backendRefs:
    - name: hubble-ui
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /

