apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: martinjcolley@gmail.com
#    server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}
