---
apiVersion: v1
kind: Namespace
metadata:
  name: wso2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: wso2
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.wso2.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wso2
  namespace: flux-system
spec:
  targetNamespace: wso2
  interval: 30m
  timeout: 30m
  chart:
    spec:
      chart: am-single-node
      version: "4.2.0-2"
      sourceRef:
        kind: HelmRepository
        name: wso2
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name:  wso2-values
