apiVersion: v1
kind: Secret
metadata:
    labels:
        cluster.x-k8s.io/provider: infrastructure-proxmox
        clusterctl.cluster.x-k8s.io: ""
        platform.ionos.com/secret-type: proxmox-credentials
    name: capmox-manager-credentials
    namespace: cluster09
stringData:
    secret: ENC[AES256_GCM,data:8wLRsdDTu7BM0G1Sej8F/Ku6CD87AZK/2xStfn1/K7XZkZpB,iv:O3bsHmcxkndzc47bg01PMRSKdW5q6LQjLEMayazMsPQ=,tag:bFRgh6wnlF3AVorKLg6SNw==,type:str]
    token: ENC[AES256_GCM,data:BLSo5RZakcjEylAplw==,iv:ut9tEwgkO00CEGHB33DasNDEnb/YoTILUOydr41dRv0=,tag:CYxL7QqBrNyHQCwmYeFVZQ==,type:str]
    url: ENC[AES256_GCM,data:5k4uf14SZp9+QTHAnpghJ9ZbENuftFl48A==,iv:JbzHB2tEDQ5jR9W6CO/ZEWpc3r4deiFJus0JLkUErC0=,tag:lQxKE/Tios5kFSUO43mfjg==,type:str]
sops:
    age:
        - recipient: age132zrzn35y4scdlcr0uale2p2x8ntta9zv40xfvyzrl4ra4j6df3scyf2dd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN2JzdFJtUHJsUjVVdTRh
            TWFvenI2RGI3VDZmOHB4cy9wMVhPM2dzTndzCmdHOU5SeWJpQXhJbVpkM3RQVWpm
            UTJNd0IrcUdnNVo0NWNyY3N4NTR5RlEKLS0tIHQvK1U5WlJ0S1BYMEpHaG1ybmNZ
            UWRiaklFa0JaTTYzbzkyZjkyUTBUVjAKf8XeG2FCLcs7ByIdvvcz24gvgFLZMTr4
            Ztg6GQAHlaQo+K0FRternE5hM1BpCWGet4k/X92CQzqqCln1jL1vWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T00:00:56Z"
    mac: ENC[AES256_GCM,data:e9GRB7UfNGh3x3L+fHrvuQC53HANNkmhth9HEeYEpog9yvFrh3lWyjW8GpTn4W3MBy5yEUsoc7W7b5UZ+6lbWInuKses4UMA7qwX/yiFjb7thMloSvXiRv3I5AAKmHIxfHzyHmpgMirR1tczS0vLcf1ass4DHzPqAXGCfs5B02w=,iv:g/jKfWxWyQJy4+xN9xq4SFThSfBrLwFNK2UuEsCpka4=,tag:KmErBo1k9SF+QsITAuy3Pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
