---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.goharbor.io/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  targetNamespace: harbor
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name:  harbor-values
