---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.goharbor.io/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  targetNamespace: harbor
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name:  harbor-values
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: harbor-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cluster09-harbor.podzone.cloud
    secretName: control-cert
  rules:
  - host: cluster09-harbor.podzone.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor
            port:
              number: 80
