apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - harbor.yaml
configMapGenerator:
  - name: harbor-values
    namespace: flux-system
    files:
      - values.yaml=harbor-values.yaml
configurations:
  - kustomizeconfig.yaml
