apiVersion: v1
kind: Namespace
metadata:
  name: snapshot
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-csi
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/kubernetes-csi/external-snapshotter.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./deploy/kubernetes/snapshot-controller
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: kubernetes-csi
  targetNamespace: snapshot
  timeout: 3m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-crd
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./client/config/crd
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: kubernetes-csi
  targetNamespace: snapshot
  timeout: 3m0s
  wait: true
