---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ws02
  namespace: flux-system
spec:
  dependsOn:
    - name: 03-storage
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops-apps/wso2
  prune: true
