apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - openclaw.yaml
  - proxmox-secret.yaml
configMapGenerator:
  - name: openclaw-values
    files:
      - values.yaml=openclaw-values.yaml
configurations:
  - kustomizeconfig.yaml
