---
apiVersion: v1
kind: Namespace
metadata:
  name: opensearch-operator 
  labels:
    pod-security.kubernetes.io/enforce: privileged

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opensearch-operator
  namespace: flux-system
spec:
  interval: 24h
  url: https://opster.github.io/opensearch-k8s-operator-chart/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch-operator
  namespace: flux-system
spec:
  targetNamespace: opensearch-operator
  interval: 30m
  timeout: 60m
  chart:
    spec:
      chart: opensearch-operator
      version: "1.0"
      sourceRef:
        kind: HelmRepository
        name: opensearch-operator
        namespace: flux-system
      interval: 12h
