---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: "{{ .Values.cluster.name }}-worker"
  namespace: "{{ .Values.cluster.name }}"
  labels:
    {{- include "cluster-chart.labels" . | nindent 4 }}
spec:
  template:
    spec:
      sourceNode: {{ .Values.proxmox.template.sourcenode }}
      templateID: {{ .Values.proxmox.template.template_vmid }}
      disks:
        bootVolume:
          disk: {{ .Values.proxmox.vm.boot_volume_device }}
          sizeGb: {{ .Values.worker.boot_volume_size }}
      format: qcow2
      full: true
      memoryMiB: {{ .Values.worker.memory_mib }}
      network:
        default:
          bridge: {{ .Values.proxmox.vm.bridge }}
          model: virtio
      numCores: {{ .Values.worker.num_cores }}
      numSockets: {{ .Values.worker.num_sockets }}
      checks:
        skipCloudInitStatus: true
        skipQemuGuestAgent: true
      metadataSettings:
        providerIDInjection: true
