---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-controlplane
  namespace: "{{ .Values.cluster.name }}"
  labels:
    {{- include "cluster-chart.labels" . | nindent 4 }}
spec:
  version: "{{ .Values.cluster.kubernetes-version }}"
  replicas: "{{ .Values.controlplane.machine-count }}"
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: "{{ .Values.cluster.name }}-controlplane"
    namespace: "{{ .Values.cluster.name }}"
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.10
      strategicPatches:
        - |
          machine:
            network:
              interfaces:
                - deviceSelector:
                    physical: true
                  vip:
                    ip: {{ .Values.controlplane.endpoint-ip }}
            install:
              disk: /dev/vda
              image: factory.talos.dev/nocloud-installer/6adc7e7fba27948460e2231e5272e88b85159da3f3db980551976bf9898ff64b:v1.11.1
            registries:
              config:
                harbor.podzone.cloud:
                  auth:
                    username: admin
                    password: Harbor12345
              mirrors:
                docker.io:
                  endpoints:
                    - https://harbor.podzone.cloud/v2/proxy-docker.io
                  overridePath: true
                ghcr.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-ghcr.io
                  overridePath: true
                gcr.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-gcr.io
                  overridePath: true
                registry.k8s.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-registry.k8s.io
                  overridePath: true
                quay.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-quay.io
                  overridePath: true
                cr.fluentbit.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-cr.fluentbit.io
                  overridePath: true
            kernel:
              modules:
                - name: drbd
                  parameters:
                    - usermode_helper=disabled
                - name: drbd_transport_tcp
            kubelet:
              extraArgs:
                rotate-server-certificates: true
                cloud-provider: external
            features:
              kubernetesTalosAPIAccess:
                enabled: true
                allowedRoles:
                  - os:reader
                allowedKubernetesNamespaces:
                  - kube-system
            sysctls:
              vm.max_map_count: 262144
          cluster:
            apiServer:
              certSANs:
                - {{ .Values.network.bastion-host-endpoint-ip }}
                - {{ .Values.network.bastion-host }}
            network:
              cni:
                name: none
            proxy:
              disabled: true
            extraManifests:
              - http://192.168.4.1/kubelet-serving-cert-approver.yaml
              - http://192.168.4.1/metrics-server.yaml
              - http://192.168.4.1/piraeus-operator.yaml
              - http://192.168.4.1/gateway-api.yaml
              - http://192.168.4.1/cilium.yaml
              - http://192.168.4.1/flux.yaml
              - http://192.168.4.1/flux-instance-observability.yaml
            externalCloudProvider:
              enabled: true
              manifests:
                - https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml

