---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluentbit
  namespace: flux-system
spec:
  interval: 24h
  url: https://fluent.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: fluent-bit
      version: "0.49.1"
      sourceRef:
        kind: HelmRepository
        name: fluentbit
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name:  fluentbit-values

---

apiVersion: v1
kind: Service
metadata:
  name: fluentbit
  namespace: kube-system
spec:
  ports:
  - name: talos
    port: 12345
    protocol: TCP
    targetPort: talos
    nodePort: 30001
  selector:
    app.kubernetes.io/instance: kube-system-fluentbit
    app.kubernetes.io/name: fluent-bit
  type: NodePort
