apiVersion: v1
kind: Secret
metadata:
    name: gitopsapi-instance-ete001
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:hjtv,iv:fFTaG8TIDzu3z2fCFBDGFFVvrInHkY91WUfKW3GJrHE=,tag:js/nAz6L7Z0DU+TX/g58sA==,type:str]
    password: ENC[AES256_GCM,data:SDMykdc+1XlSKvozKL3v0OJ7dFM9r0kZoS+ziwANdiYg2KN1l5N00sYEkvpot15fgPdegOKLVAqfckWRE9zW9Iubob7y39atXwSI2k8IyspHSgw0QAR6O21Wx3yr,iv:CbkPkP6qcBx2iGfNbSLSPdmAb/Nn85pWYuM1K3Ckq7Y=,tag:c2npaWbBEAt6TYJdD8V5Qg==,type:str]
sops:
    age:
        - recipient: age1pfhqtcg8mhwdcx5kfzft2vfshns6encg8ptyz3wwj6mlm8cgup5qcufea4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdFQ5ZGE4a2YvcWcxTW90
            SGhlMWlLMVlpZHRpeFE1QW1ZTmswNG16Y0FjCnV6Yk84MlF3YmFHNm9UVUlFcy93
            R00yQWtCTWs5Tmk2SjJCKzlmeEI2cm8KLS0tIEl6TVh3Q21abFMwM0xjSSt1alFa
            UUZwaHVoRXovSndlVWlWWk81RHZ4S0kK0YUPR8AOQ6h0gR7p54qsusXvgphPofv2
            HmarYH99ncWjSIzHqnD3XIQAK/ETx+lyCGxiSVYVUUQIk9H72N1k/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T15:46:19Z"
    mac: ENC[AES256_GCM,data:EvWES3ZoOVeq70tFxuTeW5PdDqtout6o2Z7FRE2sqSBv0o5VaPzmnhs54Cfm40RTlHqE0nEVAInJG33W9bFI8Ds2Xi0kxTVBiQrV7YAcSH0LmJCNrkkkhujeJLkA+Dmq14cF/M95WQ3WVm1izemKFtzU7bqB+QILA7fTJfQaY4o=,iv:VKYLnEwhqyX6B2pRATHdDpxUpEYQIuTnF/1HCD6MYgM=,tag:eeSHsN2J6j9JjQlgzLXrUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
