apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podzone-docs
resources:
  - podzone-docs.yaml
configMapGenerator:
  - name: podzone-docs-values
    files:
      - values.yaml=./podzone-docs-values.yaml
configurations:
  - kustomizeconfig.yaml