---
apiVersion: v1
kind: Namespace
metadata:
  name: "${CLUSTER_NAME}"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-proxmox
    clusterctl.cluster.x-k8s.io: ""
  name: capmox-manager-credentials
  namespace: "${CLUSTER_NAME}"
stringData:
  secret: "${PROXMOX_SECRET}"
  token: "${PROXMOX_TOKEN}"
  url: "${PROXMOX_URL}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-controlplane"
  namespace: "${CLUSTER_NAME}"
spec:
  template:
    spec:
      sourceNode: "${PROXMOX_SOURCENODE}"
      templateID: ${TEMPLATE_VMID}
      disks:
        bootVolume:
          disk: ${BOOT_VOLUME_DEVICE}
          sizeGb: ${BOOT_VOLUME_SIZE:=40}
      format: qcow2
      full: true
      memoryMiB: ${MEMORY_MIB:=16384}
      network:
        default:
          bridge: ${BRIDGE}
          model: virtio
      numCores: ${NUM_CORES:=2}
      numSockets: ${NUM_SOCKETS:=2}
      checks:
        skipCloudInitStatus: true
        skipQemuGuestAgent: true
      metadataSettings:
        providerIDInjection: true
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-worker"
  namespace: "${CLUSTER_NAME}"
spec:
  template:
    spec:
      sourceNode: "${PROXMOX_SOURCENODE}"
      templateID: ${TEMPLATE_VMID}
      disks:
        bootVolume:
          disk: ${BOOT_VOLUME_DEVICE}
          sizeGb: ${BOOT_VOLUME_SIZE:=40}
      format: qcow2
      full: true
      memoryMiB: ${MEMORY_MIB:=16384}
      network:
        default:
          bridge: ${BRIDGE}
          model: virtio
      numCores: ${NUM_CORES:=2}
      numSockets: ${NUM_SOCKETS:=2}
      checks:
        skipCloudInitStatus: true
        skipQemuGuestAgent: true
      metadataSettings:
        providerIDInjection: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-controlplane
  namespace: "${CLUSTER_NAME}"
spec:
  version: "${KUBERNETES_VERSION}"
  replicas: ${CONTROL_PLANE_MACHINE_COUNT:=1}
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: "${CLUSTER_NAME}-controlplane"
    namespace: "${CLUSTER_NAME}"
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.10
      strategicPatches:
        - |
          machine:
            network:
              interfaces:
                - deviceSelector:
                    physical: true
                  vip:
                    ip: ${CONTROL_PLANE_ENDPOINT_IP}
            install:
              disk: /dev/vda
              image: factory.talos.dev/nocloud-installer/6adc7e7fba27948460e2231e5272e88b85159da3f3db980551976bf9898ff64b:v1.11.1
            registries:
              config:
                harbor.podzone.cloud:
                  auth:
                    username: admin
                    password: Harbor12345
              mirrors:
                docker.io:
                  endpoints:
                    - https://harbor.podzone.cloud/v2/proxy-docker.io
                  overridePath: true
                ghcr.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-ghcr.io
                  overridePath: true
                gcr.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-gcr.io
                  overridePath: true
                registry.k8s.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-registry.k8s.io
                  overridePath: true
                quay.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-quay.io
                  overridePath: true
                cr.fluentbit.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-cr.fluentbit.io
                  overridePath: true
            kernel:
              modules:
                - name: drbd
                  parameters:
                    - usermode_helper=disabled
                - name: drbd_transport_tcp
            kubelet:
              extraArgs:
                rotate-server-certificates: true
                cloud-provider: external
            features:
              kubernetesTalosAPIAccess:
                enabled: true
                allowedRoles:
                  - os:reader
                allowedKubernetesNamespaces:
                  - kube-system
            sysctls:
              vm.max_map_count: 262144
          cluster:
            apiServer:
              certSANs:
                - ${BASTION_HOST_ENDPOINT_IP}
                - ${BASTION_HOST}
            network:
              cni:
                name: none
            proxy:
              disabled: true
            extraManifests:
              - http://192.168.4.5/kubelet-serving-cert-approver.yaml
              - http://192.168.4.5/metrics-server.yaml
              - http://192.168.4.5/piraeus-operator.yaml
              - http://192.168.4.5/gateway-api.yaml
              - http://192.168.4.5/cilium.yaml
            externalCloudProvider:
              enabled: true
              manifests:
                - https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml

---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talosconfig-worker
  namespace: "${CLUSTER_NAME}"
  labels:
    cluster-name: "${CLUSTER_NAME}"
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v1.10
      strategicPatches:
        - |
          machine:
            install:
              disk: /dev/vda
              image: factory.talos.dev/nocloud-installer/6adc7e7fba27948460e2231e5272e88b85159da3f3db980551976bf9898ff64b:v1.11.1
            registries:
              config:
                harbor.podzone.cloud:
                  auth:
                    username: admin
                    password: Harbor15194
              mirrors:
                docker.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-docker.io
                  overridePath: true
                ghcr.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-ghcr.io
                  overridePath: true
                gcr.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-gcr.io
                  overridePath: true
                registry.k8s.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-registry.k8s.io
                  overridePath: true
                quay.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-quay.io
                  overridePath: true
                cr.fluentbit.io:
                  endpoints:
                    - http://harbor.podzone.cloud/v2/proxy-cr.fluentbit.io
                  overridePath: true
            sysctls:
              vm.max_map_count: 262144
            kernel:
              modules:
                - name: drbd
                  parameters:
                    - usermode_helper=disabled
                - name: drbd_transport_tcp
            kubelet:
              extraArgs:
                rotate-server-certificates: true
                cloud-provider: external
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-workers"
  namespace: "${CLUSTER_NAME}"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT:=1}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: talosconfig-worker
          namespace: "${CLUSTER_NAME}"
      clusterName: "${CLUSTER_NAME}"
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: "${CLUSTER_NAME}-worker"
        namespace: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: proxmox-cluster
  namespace: "${CLUSTER_NAME}"
spec:
  schedulerHints:
    memoryAdjustment: 0
  allowedNodes: ${ALLOWED_NODES:=[]}
  controlPlaneEndpoint:
    host: ${CONTROL_PLANE_ENDPOINT_IP}
    port: 6443
  dnsServers: ${DNS_SERVERS}
  ipv4Config:
    addresses: ${NODE_IP_RANGES}
    gateway: ${GATEWAY}
    prefix: ${IP_PREFIX}
  credentialsRef:
    name: capmox-manager-credentials
    namespace: "${CLUSTER_NAME}"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
  namespace: "${CLUSTER_NAME}"
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: talos-controlplane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: proxmox-cluster
---
