apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - qdrant.yaml
configMapGenerator:
  - name: qdrant-values
    namespace: flux-system
    files:
      - values.yaml=qdrant-values.yaml
configurations:
  - kustomizeconfig.yaml
