apiVersion: v1
kind: Secret
metadata:
    name: gitopsapi-github-token
    namespace: gitopsapi
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:kcuM+28dFvWPA3YCveHZpQr5RAglfeXPqgk1W8rOgc319HC1tKTOw4I5iJo1vC+zdyHN1OREVIEU3JuAb3B1b+BX/+IqeRvtliYMwqANKP4q6PNbs0+mGBihQFiZ,iv:PtU4pbHfJRz9Oucj/CtUkgRPCMpUMTgVqQ7V/T01M6c=,tag:m/Tw16ojfCsiUJODV5nTeg==,type:str]
sops:
    age:
        - recipient: age132zrzn35y4scdlcr0uale2p2x8ntta9zv40xfvyzrl4ra4j6df3scyf2dd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb1YzVmdlbGRaSkU4OElX
            dWJTdkE3LzlSZWVVcjRFOWJaM3RoQVROdzBrCng4RDcyWFZXaThLOEg5eGNiMExB
            WnAwVlhjbGJXNE81Q3pNcE1hUnZvR0UKLS0tIEN0ZmVRWTdvNUptSEI4c29EZHJY
            Z3crRzIrT3h6OEZWTnVWbmw5Y0szZ2cK0RraRBSQUYE/9zfi0NJRsojYhbmPKWp1
            S/+EO2L4JNR7jMqdFkDq3jOEf6xwXwfZuy2qs5rkWFvWP7UVCEe0bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T00:03:57Z"
    mac: ENC[AES256_GCM,data:FbsbAEHLtPj+kFchB/yE36AfUsT8hXHTmR/b7h249MpmKj63kRtox+YuBIFTXSZsb+ynYkR2uSsPllacQMOZcZheio7IVeKcNUIWa+q8lI+fV26bmgVByNKw44FKfLAOkN/wj9MWmxnvnN4XAFiNbfrKuZrVOaMiQ8ZiYeSNavw=,iv:TQgebPVYfkdsqzDdnUpL5fgJPm28sXhm8vFA7Y5U2pE=,tag:gycGvGfW8k/rVZw4zkpEVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
