---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  gatewayClassName: cilium
  listeners:
  - hostname: harbor.podzone.cloud
    name: harbor-podzone-cloud
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: harbor-secret
    allowedRoutes:
      namespaces:
        from: All
  - hostname: cluster09-docs.podzone.cloud
    name: cluster09-docs-podzone-cloud
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: cluster09-docs-secret
    allowedRoutes:
      namespaces:
        from: All
  - hostname: hubble.podzone.cloud
    name: hubble-podzone-cloud
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: hubble-secret
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: martinjcolley@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: gateway
                namespace: kube-system
                kind: Gateway
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller