apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.yaml
configMapGenerator:
  - name: prometheus-values
    namespace: flux-system
    files:
      - values.yaml=prometheus-values.yaml
configurations:
  - kustomizeconfig.yaml
